version: "2"

volumes:
  ndistc_data:

services:
  ndistc:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    image: ghcr.io/jehoonsong/ndist-boinc:latest
    environment:
      - BOINC_CMD_LINE_OPTIONS=--dir /var/lib/boinc --allow_remote_gui_rpc --attach_project ${BOINC_PROJECT_URL} ${BOINC_ACCOUNT_KEY}
      - BOINC_REMOTE_HOST=${BOINC_REMOTE_HOST}
      - BOINC_PROJECT_URL=${BOINC_PROJECT_URL}
      - BOINC_ACCOUNT_KEY=${BOINC_ACCOUNT_KEY}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ndistc_data:/var/lib/boinc
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
        #- ./cc_config.xml:/var/lib/boinc/cc_config.xml
        #- ./app_config.xml:/var/lib/boinc/projects/${BOINC_REMOTE_HOST}_8089_ndist/app_config.xml
        #- ./global_prefs_override.xml:/var/lib/boinc/global_prefs_override.xml
        #- ./remote_hosts.cfg:/var/lib/boinc/remote_hosts.cfg
    ports:
      - "31416:31416"   

    restart: unless-stopped
